services:
 web:
   image: dairoot/chatgpt-mirror:latest
   restart: always
   env_file:
     - .env
   labels:
     - "com.centurylinklabs.watchtower.enable=true"
   environment:
     - CHATGPT_GATEWAY_URL=http://gateway:8787
   ports:
     - "50002:50002"
   volumes:
     - chatgpt_mirror_db:/app/backend/db/
     - ./backend/logs:/app/backend/logs
   networks:
     - dokploy-network

 gateway:
   image: dairoot/chatgpt-gateway:latest
   restart: always
   env_file:
     - .env
   labels:
     - "com.centurylinklabs.watchtower.enable=true"
   deploy:
     replicas: 1
   depends_on:
     - redis
   environment:
     - REDIS_URL=redis://redis:6379/0
   networks:
     - dokploy-network

 cf5s:
   image: dairoot/cf5s:latest
   restart: always
   env_file:
     - .env
   labels:
     - "com.centurylinklabs.watchtower.enable=true"
   depends_on:
     - gateway
   environment:
     - CHATGPT_GATEWAY_URL=http://gateway:8787
   networks:
     - dokploy-network

 redis:
   image: redis:latest
   restart: always
   volumes:
     - chatgpt_gateway_db:/data
   command: ["redis-server", "--appendonly", "yes"]
   networks:
     - dokploy-network

 watchtower:
   image: containrrr/watchtower
   restart: unless-stopped
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   command: --cleanup --interval 3600 --label-enable
   networks:
     - dokploy-network

volumes:
 chatgpt_mirror_db:
 chatgpt_gateway_db:
